version: '3.6'

services:

  web:
    container_name: 'api-identity'
    image: 'api-identity'
    build:
      context: .
      dockerfile: apiIdentity.development.dockerfile
    volumes:
      - .:/var/www/apiIdentity
    ports:
     - "5000:5000"
    depends_on:
     - "postgres"
    networks:
      - api-identity-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - api-identity-network

networks:
  api-identity-network:
    driver: bridge


