version: '3.6'

services:
  gateway:
    build:
      context: krakend-ce
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./gateway:/etc/krakend
    ports:
      - 8090:8090
    command: [ "run", "-c", "/etc/krakend/config.json" ]

#  identity:
#    container_name: 'identity'
#    image: 'Identity'
#    build:
#      context: ./Identity
#      dockerfile: identity.development.dockerfile
#    volumes:
#      - ./Identity:/var/www/Identity
#    depends_on:
#      - "postgres"
#    networks:
#      - identity-network

#  postgres:
#    container_name: 'postgres'
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: password
#    networks:
      - identity-network
#networks:
#  identity-network:
#    driver: bridge


