version: '3.6'

services:
  gateway:
    build:
      context: krakend-ce
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./gateway:/etc/krakend
    ports:
      - 8080:8080
    command: [ "run", "-c", "/etc/krakend/config.json" ]
    depends_on:
    - identity
    - static_data
  static_data:
    image: jaxgeller/lwan
    container_name: 'static_data'
    volumes:
      - ./static_data:/lwan/wwwroot
    ports:
      - "8000:8080"
  identity:
    container_name: 'identity'
    image: 'identity'
    build:
      context: ./Identity
      dockerfile: development.dockerfile
    ports:
      - 5000:5000
  predict:
    container_name: 'predict'
    image: 'predict'
    build:
      context: ./predict
      dockerfile: Dockerfile
    ports:
      - 5001:5000
  ml_worker:
    container_name: 'ml_worker'
    image: 'ml_worker'
    build:
      context: ./ml_worker
      dockerfile: Dockerfile
    volumes:
      - ./snapshotes:/app/snapshotes
    ports:
      - 5002:5000