---

- hosts: all
  become: yes
  tasks:
  - name: Install ftpd
    apt:
      name:
      - vsftpd
      state: latest
  # - name: take backup of existing config
  #   copy:
  #     src: /etc/vsftpd.conf
  #     dest: /etc/vsftpd.conf.bkp
  #     remote_src: yes
  - name: write config
    template: 
      src: vsftpd.j2
      dest: /etc/vsftpd.conf
    notify:
      - restart vsftpd
  - name: start vsftpd
    service: name=vsftpd state=started

  handlers:
    - name: restart vsftpd
      service: name=vsftpd state=restarted