---

- hosts: ftp_server
  become: yes
  tasks:
  - name: Ensures dir exists
    file: path=/etc/lacmus/DockerFiles/ftp state=directory
  - name: Ensure logs dir
    file: path=/etc/lacmus/logs state=directory
  - name: Copy ftp api
    copy: 
      src : ../../ftp_api
      dest : /etc/lacmus/DockerFiles/ftp
  - name: Copy local files
    copy: 
      src : DockerFiles/ftp/
      dest : /etc/lacmus/DockerFiles/ftp      
  - name: Build image
    docker_image:
      name: vsftpd
      build:
        path: /etc/lacmus/DockerFiles/ftp
        pull: yes
      force_source: yes
      source: build
    notify:
      - restart container
  - name: start ftp docker
    docker_container:
      name: ftp
      image: vsftpd
      state: started
      network_mode: host
      published_ports:
        - "0.0.0.0:21:21"
        - "127.0.0.1:5001:5001"
      mounts:
        -
          source: /etc/lacmus/logs
          target: /root/ftp_api/logs
          type: bind
      env:
        POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"
        MINIO_ACCESS_KEY: "{{ lookup('env','MINIO_ACCESS_KEY') }}"
        MINIO_SECRET_KEY: "{{ lookup('env','MINIO_SECRET_KEY') }}"

  handlers:
  - name: restart container
    docker_container:
      name: ftp
      image: vsftpd
      restart: yes
