---

- hosts: dev_servers
  become: yes
  tasks:
  - name: Ensures dir exists
    file: path=/etc/lacmus/DockerFiles/ftp state=directory    
  - name: prepare config
    template: 
      src: DockerFiles/ftp/vsftpd.j2
      dest: /etc/lacmus/DockerFiles/ftp/vsftpd.conf
  - name: prepare dockerfile
    template: 
      src: DockerFiles/ftp/Dockerfile
      dest: /etc/lacmus/DockerFiles/ftp/Dockerfile
    notify:
      Build image
  - name: start ftp docker
    docker_container:
      name: ftp
      image: vsftpd
      state: started
      published_ports:
        0.0.0.0:21:21
      detach: true
      tty: true

  handlers:
  - name: Build image
    docker_image:
      name: vsftpd
      build:
        path: /etc/lacmus/DockerFiles/ftp
        pull: yes
      force_source: yes
      source: build
    notify:
      - restart container
  - name: restart container
    docker_container:
      name: ftp
      image: vsftpd
      restart: yes
