---

- hosts: identity_api
  become: yes
  tasks:
  - name: Copy identity api
    copy: 
      src : ../../identity_api
      dest : /etc/lacmus/DockerFiles/identity
  - name: Copy local files
    copy: 
      src : DockerFiles/identity/
      dest : /etc/lacmus/DockerFiles/identity      
  - name: Build image
    docker_image:
      name: identity_api
      build:
        path: /etc/lacmus/DockerFiles/identity
        pull: yes
      force_source: yes
      source: build
    notify:
      - restart container
  - name: start ftp docker
    docker_container:
      name: identity
      image: identity_api
      state: started
      published_ports:
        - "0.0.0.0:5002:5002"
      env:
        POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"
        MINIO_ACCESS_KEY: "{{ lookup('env','MINIO_ACCESS_KEY') }}"
        MINIO_SECRET_KEY: "{{ lookup('env','MINIO_SECRET_KEY') }}"

  handlers:
  - name: restart container
    docker_container:
      name: identity
      image: identity_api
      restart: yes
