---

- hosts: orchestrator
  become: yes
  tasks:
  - name: Copy orchestrator
    copy: 
      src : ../../orchestrator
      dest : /etc/lacmus/DockerFiles/orchestrator
  - name: Copy local files
    copy: 
      src : DockerFiles/orchestrator/
      dest : /etc/lacmus/DockerFiles/orchestrator      
  - name: Build image
    docker_image:
      name: orchestrator
      build:
        path: /etc/lacmus/DockerFiles/orchestrator
        pull: yes
      force_source: yes
      source: build
    notify:
      - restart container
  - name: start orchestrator docker
    docker_container:
      name: orchestrator_instance
      image: orchestrator
      network_mode: host
      state: started
      env:
        POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"
        MINIO_ACCESS_KEY: "{{ lookup('env','MINIO_ACCESS_KEY') }}"
        MINIO_SECRET_KEY: "{{ lookup('env','MINIO_SECRET_KEY') }}"

  handlers:
  - name: restart container
    docker_container:
      name: orchestrator_instance
      image: orchestrator
      restart: yes
